<?php

namespace common\models;

use Imagine\Image\Box;
use Imagine\Imagick\Imagine;
use Yii;
use yii\helpers\FileHelper;
use yii\imagine\Image;

/**
 * This is the model class for table "car".
 *
 * @property string $id
 * @property string|null $car_model
 * @property string|null $car_name
 * @property string|null $car_type
 * @property int $car_price
 * @property int|null $car_status
 * @property string $from_date
 * @property string $to_date
 *
 * @property Rent[] $rents
 */
class Car extends \yii\db\ActiveRecord
{
    public $car;
    const STATUS_AVAILABLE="AVAILABLE";
    const STATUS_UNAVAILABLE="UNAVAILABLE";
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'car';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id',], 'required'],
            [['car_price',], 'integer'],
            [['car_status',], 'string', 'max' => 16],
            [['id'], 'string', 'max' => 16],
            [['car_model', 'car_name', 'car_type'], 'string', 'max' => 100],
            [['id'], 'unique'],
            ['car_status', 'default', 'value'=>self::STATUS_AVAILABLE],
            ['from_date', 'date', 'timestampAttribute' => 'from_date'],
            ['to_date', 'date', 'timestampAttribute' => 'to_date'],
            ['car', 'image'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'car_model' => Yii::t('app', 'Car Model'),
            'car_name' => Yii::t('app', 'Car Name'),
            'car_type' => Yii::t('app', 'Car Type'),
            'car_price' => Yii::t('app', 'Car Price'),
            'car_status' => Yii::t('app', 'Car Status'),
            'from_date' => Yii::t('app', 'From Date'),
            'to_date' => Yii::t('app', 'To Date'),
        ];
    }

    /**
     * Gets query for [[Rents]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getRents()
    {
        return $this->hasMany(Rent::className(), ['car_id' => 'id']);
    }

    public function getStatus(){
        return [
            self::STATUS_AVAILABLE=>'AVAILABLE',
            self::STATUS_UNAVAILABLE=>'UNAVAILABLE',
        ];
    }

    public function save($runValidation = true, $attributeNames = null)
    {
        $isInsert =$this->isNewRecord;
        if ($isInsert) {
            $this->id =Yii::$app->security->generateRandomString(8);
        }
        $saved = parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        if (!$saved) {
            return false;
        }
        if ($isInsert) {
            $carPath =Yii::getAlias('@frontend/web/images/car' .$this->id.'.JPG');
            if (!is_dir(dirname($carPath))) {
                FileHelper::createDirectory(dirname($carPath));
            }
            $this->car->saveAs($carPath);
            Image::getImagine()
                ->open($carPath)
                ->thumbnail(new Box(1280, 1280))
                ->save();
        }
        return true;
    }
    public function getCarLink() {

        return Yii::$app->params['frontendUrl'].'/images/car'.$this->id.'.JPG';
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        $carPath =Yii::getAlias('@frontend/web/images/car' .$this->id.'.JPG');
        if (file_exists($carPath)) {
            unlink($carPath);
        }
    }
}
