<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "rent".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string $car_id
 * @property string $name
 * @property string $email
 * @property string $order_at
 * @property int $from_date
 * @property int $to_date
 *
 * @property Car $car
 * @property User $user
 */
class Rent extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'rent';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', ], 'integer'],
            [['car_id', 'name', 'email', 'order_at', 'from_date', 'to_date'], 'required'],
            ['email', 'email'],
            [['car_id', 'name', 'email'], 'string', 'max' => 100],
            ['from_date', 'date', 'timestampAttribute' => 'from_date'],
            ['to_date', 'date', 'timestampAttribute' => 'to_date'],
            [['car_id'], 'exist', 'skipOnError' => true, 'targetClass' => Car::className(), 'targetAttribute' => ['car_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'car_id' => Yii::t('app', 'Car ID'),
            'name' => Yii::t('app', 'Name'),
            'email' => Yii::t('app', 'Email'),
            'order_at' => Yii::t('app', 'Order At'),
            'from_date' => Yii::t('app', 'From Date'),
            'to_date' => Yii::t('app', 'To Date'),
        ];
    }

    /**
     * Gets query for [[Car]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getCar()
    {
        return $this->hasOne(Car::className(), ['id' => 'car_id']);
    }

    /**
     * Gets query for [[User]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getCarLink() {

        return Yii::$app->params['frontendUrl'].'/images/car'.$this->car_id.'.JPG';
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $model1 = Car::findOne($this->car_id);
        $model1->car_status="UNAVAILABLE";
        $model1->save(false);
    }

}
