<?php

namespace common\models;

use Yii;
use yii\helpers\FileHelper;

/**
 * This is the model class for table "backup".
 *
 * @property string $id
 * @property string|null $car_model
 * @property string|null $car_name
 * @property string|null $car_status
 * @property string|null $from
 * @property string|null $to
 */
class Car extends \yii\db\ActiveRecord
{
    public $car;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'backup';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id',], 'required'],
            [['car_status'], 'string'],
            [['id'], 'string', 'max' => 10],
            [['car_price'], 'integer'],
            [['car_model', 'car_name',], 'string', 'max' => 100],
            [['id'], 'unique'],
            ['car_status', 'default', 'value' => '0'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'car_model' => Yii::t('app', 'back Model'),
            'car_name' => Yii::t('app', 'back Name'),
            'car_price' => Yii::t('app', 'back Price'),
            'car_status' => Yii::t('app', 'back Status'),
            'from' => Yii::t('app', 'From'),
            'to' => Yii::t('app', 'To'),
        ];
    }
    public function save($runValidation = true, $attributeNames = null)
    {
        $isInsert =$this->isNewRecord;
        if ($isInsert) {
            $this->id =Yii::$app->security->generateRandomString(8);
        }
        $saved = parent::save($runValidation, $attributeNames); // TODO: Change the autogenerated stub
        if (!$saved) {
            return false;
        }
        if ($isInsert) {
            $carPath =Yii::getAlias('@frontend/web/images/backup' .$this->id.'.JPG');
            if (!is_dir(dirname($carPath))) {
                FileHelper::createDirectory(dirname($carPath));
            }
            $this->car->saveAs($carPath);
        }
        return true;
    }
    public function getCarLink() {

        return Yii::$app->params['frontendUrl'].'/images/backup'.$this->id.'.JPG';
    }

    public function afterDelete()
    {
        parent::afterDelete(); // TODO: Change the autogenerated stub
        $carPath =Yii::getAlias('@frontend/web/images/backup' .$this->id.'.JPG');
        unlink($carPath);
    }
}
